---
development:
  # sqlite
  # db_filename: infrastructure/database/dev.db
  #PostgreSQL
  db_name: translate_this_dev

test:
  # sqlite
  # db_filename: infrastructure/database/test.db
  #PostgreSQL
  db_name: translate_this_test
  
